### PR TITLE
Use syrupy for dict assertions

### PR DESCRIPTION
**Pull request by joostlek**
# Proposed Changes

Since with every license plate extra we want to test, the list of assertions grow bigger and bigger, so why not use snapshots

### CODE REVIEW

**Comment by joostlek** [comment]
Boop

**Comment by joostlek** [comment]
Beep

**Review by frenck — CHANGES_REQUESTED** [review]
Merge conflicts 🙈

**Comment by joostlek** [comment]
smh my head

**Review by frenck — APPROVED** [review]

**Pull request merged**
